import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../models/blog_post.dart';
import '../../models/user_model.dart';
import '../../providers/auth_provider.dart';
import '../../providers/blog_provider.dart';
import '../../providers/tag_provider.dart';

class CreatePostScreen extends ConsumerStatefulWidget {
  const CreatePostScreen({super.key});

  @override
  ConsumerState<CreatePostScreen> createState() => _CreatePostScreenState();
}

class _CreatePostScreenState extends ConsumerState<CreatePostScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _contentController = TextEditingController();
  final List<int> _selectedTags = [];
  bool _isLoading = false;

  @override
  void dispose() {
    _titleController.dispose();
    _contentController.dispose();
    super.dispose();
  }

  Future<void> _submitPost() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedTags.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select at least one tag')),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final user = ref.read(authStateProvider).valueOrNull;
      if (user == null) throw Exception('User not logged in');

      final postId = DateTime.now().millisecondsSinceEpoch;

      final newPost = BlogPost(
        id: '', // Generated by backend
        postId: postId, // Generate a unique ID
        title: _titleController.text,
        subtitle: '', // Optional/Default
        content: _contentController.text,
        authorName: user.name,
        authorAvatarUrl: '', // Optional
        publishDate: DateTime.now(),
        readTimeMinutes: (_contentController.text.split(' ').length / 200).ceil(),
        clapCount: 0,
        tags: [], // Tags are now handled via noted_post-tabs
        imageUrl: null, // Optional
        isPublished: true,
      );

      await ref.read(blogRepositoryProvider).createBlogPost(newPost);
      await ref.read(blogRepositoryProvider).addTagsToPost(postId, _selectedTags);
      
      // Refresh the list
      ref.invalidate(blogListProvider);
      
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Post created successfully!')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error creating post: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    final tagsAsync = ref.watch(tagListProvider);

    return Scaffold(
      backgroundColor: theme.scaffoldBackgroundColor,
      appBar: AppBar(
        backgroundColor: colorScheme.surface,
        title: Text(
          'Create New Post',
          style: GoogleFonts.merriweather(
            color: colorScheme.onSurface,
            fontWeight: FontWeight.bold,
          ),
        ),
        iconTheme: IconThemeData(color: colorScheme.onSurface),
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: 16.0),
            child: TextButton(
              onPressed: _isLoading ? null : _submitPost,
              style: TextButton.styleFrom(
                backgroundColor: colorScheme.primary,
                foregroundColor: colorScheme.onPrimary,
              ),
              child: _isLoading
                  ? SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        color: colorScheme.onPrimary,
                      ),
                    )
                  : Text(
                      'Publish',
                      style: GoogleFonts.spaceMono(fontWeight: FontWeight.bold),
                    ),
            ),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TextFormField(
                controller: _titleController,
                style: GoogleFonts.merriweather(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                  color: colorScheme.onSurface,
                ),
                decoration: InputDecoration(
                  hintText: 'Title',
                  hintStyle: TextStyle(color: colorScheme.onSurface.withOpacity(0.5)),
                  border: InputBorder.none,
                ),
                validator: (value) =>
                    value == null || value.isEmpty ? 'Please enter a title' : null,
              ),
              const SizedBox(height: 24),
              Text(
                'Tags',
                style: GoogleFonts.spaceMono(
                  fontSize: 14,
                  fontWeight: FontWeight.bold,
                  color: colorScheme.onSurface,
                ),
              ),
              const SizedBox(height: 8),
              tagsAsync.when(
                data: (tags) => Wrap(
                  spacing: 8,
                  runSpacing: 8,
                  children: tags.map((tag) {
                    final isSelected = _selectedTags.contains(tag.tagId);
                    return FilterChip(
                      label: Text(tag.tagName),
                      selected: isSelected,
                      onSelected: (selected) {
                        setState(() {
                          if (selected) {
                            _selectedTags.add(tag.tagId);
                          } else {
                            _selectedTags.remove(tag.tagId);
                          }
                        });
                      },
                      labelStyle: GoogleFonts.spaceMono(
                        color: isSelected ? colorScheme.onPrimary : colorScheme.onSurface,
                      ),
                      backgroundColor: colorScheme.surface,
                      selectedColor: colorScheme.primary,
                      checkmarkColor: colorScheme.onPrimary,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                        side: BorderSide(color: colorScheme.onSurface.withOpacity(0.2)),
                      ),
                    );
                  }).toList(),
                ),
                loading: () => const LinearProgressIndicator(),
                error: (err, _) => Text('Error loading tags: $err'),
              ),
              const SizedBox(height: 24),
              TextFormField(
                controller: _contentController,
                style: GoogleFonts.merriweather(
                  fontSize: 16,
                  color: colorScheme.onSurface,
                  height: 1.6,
                ),
                decoration: InputDecoration(
                  hintText: 'Write your story...',
                  hintStyle: TextStyle(color: colorScheme.onSurface.withOpacity(0.5)),
                  border: InputBorder.none,
                ),
                maxLines: null,
                validator: (value) =>
                    value == null || value.isEmpty ? 'Please write some content' : null,
              ),
            ],
          ),
        ),
      ),
    );
  }
}
