import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../providers/auth_provider.dart';
import '../../models/user_model.dart';
import '../../providers/tag_provider.dart';
import '../../models/tag_model.dart';
import '../../providers/blog_provider.dart';

class TagSidebar extends ConsumerWidget {
  const TagSidebar({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    final tagsAsync = ref.watch(tagListProvider);
    final authState = ref.watch(authStateProvider);
    final isAdmin = authState.valueOrNull?.role == UserRole.admin;

    return Container(
      width: 250,
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        border: Border(right: BorderSide(color: colorScheme.onSurface.withOpacity(0.1))),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Tags',
                style: GoogleFonts.merriweather(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: colorScheme.onSurface,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          Expanded(
            child: tagsAsync.when(
              data: (tags) => ListView.separated(
                itemCount: tags.length,
                separatorBuilder: (_, __) => const SizedBox(height: 8),
                itemBuilder: (context, index) {
                  final tag = tags[index];
                  return _TagItem(tag: tag, isAdmin: isAdmin);
                },
              ),
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (err, stack) => Text('Error: $err'),
            ),
          ),
          if (isAdmin) ...[
            const SizedBox(height: 16),
            SizedBox(
              width: double.infinity,
              child: OutlinedButton.icon(
                onPressed: () => _showAddTagDialog(context, ref),
                icon: const Icon(Icons.add),
                label: const Text('Add Tag'),
                style: OutlinedButton.styleFrom(
                  foregroundColor: colorScheme.onSurface,
                  side: BorderSide(color: colorScheme.onSurface),
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }

  void _showAddTagDialog(BuildContext context, WidgetRef ref) {
    final nameController = TextEditingController();
    final slugController = TextEditingController();
    final descriptionController = TextEditingController();

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Add New Tag'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              controller: nameController,
              decoration: const InputDecoration(labelText: 'Tag Name'),
            ),
            TextField(
              controller: slugController,
              decoration: const InputDecoration(labelText: 'Slug'),
            ),
            TextField(
              controller: descriptionController,
              decoration: const InputDecoration(labelText: 'Description'),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () {
              final tag = Tag(
                id: '', // ID is generated by backend
                tagId: DateTime.now().millisecondsSinceEpoch, // Temporary int ID
                tagName: nameController.text,
                slug: slugController.text,
                description: descriptionController.text,
              );
              ref.read(tagListProvider.notifier).addTag(tag);
              Navigator.pop(context);
            },
            child: const Text('Add'),
          ),
        ],
      ),
    );
  }
}

class _TagItem extends ConsumerWidget {
  final Tag tag;
  final bool isAdmin;

  const _TagItem({required this.tag, required this.isAdmin});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    final selectedTag = ref.watch(selectedTagProvider);
    final isSelected = selectedTag == tag.tagName;

    return Row(
      children: [
        Expanded(
          child: InkWell(
            onTap: () {
              if (isSelected) {
                ref.read(selectedTagProvider.notifier).setTag(null);
              } else {
                ref.read(selectedTagProvider.notifier).setTag(tag.tagName);
              }
            },
            child: Container(
              padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 12),
              decoration: BoxDecoration(
                color: isSelected ? colorScheme.primary : colorScheme.surface,
                border: Border.all(color: colorScheme.onSurface.withOpacity(0.2)),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Text(
                tag.tagName,
                style: GoogleFonts.spaceMono(
                  fontSize: 14,
                  color: isSelected ? colorScheme.onPrimary : colorScheme.onSurface,
                  fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                ),
              ),
            ),
          ),
        ),
        if (isAdmin)
          IconButton(
            icon: const Icon(Icons.delete_outline, size: 18),
            onPressed: () {
              // Confirm delete
              showDialog(
                context: context,
                builder: (context) => AlertDialog(
                  title: const Text('Delete Tag'),
                  content: Text('Are you sure you want to delete "${tag.tagName}"?'),
                  actions: [
                    TextButton(
                      onPressed: () => Navigator.pop(context),
                      child: const Text('Cancel'),
                    ),
                    TextButton(
                      onPressed: () {
                        ref.read(tagListProvider.notifier).deleteTag(tag.id);
                        Navigator.pop(context);
                      },
                      child: const Text('Delete', style: TextStyle(color: Colors.red)),
                    ),
                  ],
                ),
              );
            },
          ),
      ],
    );
  }
}
